<a href="https://colab.research.google.com/github/wrixd/numpy_exercise/blob/main/15_Create_a_2d_array_with_1_on_the_border_and_0_inside.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import numpy as np

In [37]:
a=np.ones([6,6],dtype='int32')
print(a)
b=np.zeros([4,4],dtype='int32');print(b)


[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [39]:
a[1:-1,1:-1]=b
print(a)

[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]
