<a href="https://colab.research.google.com/github/wrixd/numpy_exercise/blob/main/16_How_to_add_a_border_(filled_with_0's)_around_an_existing_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [63]:
import numpy as np

In [64]:
a= np.random.randint(1,200,size=(6,6),dtype='int32')

In [65]:
print(a)

[[199  54  58  54 126 146]
 [193 189 190 143 116 131]
 [  6 104  32  20  53 129]
 [178 189 104  93  22 128]
 [115 148 164 100  15  25]
 [ 54 120  92  11  38 150]]


In [66]:
b=np.zeros((4,4))

In [67]:
a[:,0]= 0; a[0,:]=0;a[-1,:]=0;a[:,-1]=0

In [68]:
print(a)

[[  0   0   0   0   0   0]
 [  0 189 190 143 116   0]
 [  0 104  32  20  53   0]
 [  0 189 104  93  22   0]
 [  0 148 164 100  15   0]
 [  0   0   0   0   0   0]]
