<a href="https://colab.research.google.com/github/wrixd/numpy_exercise/blob/main/18_Create_a_5x5_matrix_with_values_1%2C2%2C3%2C4_just_below_the_diagonal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [50]:
import numpy as np

In [51]:
a= np.zeros((5,5) )
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [52]:
j=1;k=1
for i in range(1,5):
  a[i,j-1] = k  
  j=j+1;k+=1

In [53]:
print(a)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]
