<a href="https://colab.research.google.com/github/wrixd/numpy_exercise/blob/main/21_Create_a_checkerboard_8x8_matrix_using_the_tile_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np

In [19]:
A = np.array([[[[[[[[0,1],[0,1],[0,1],[0,1],[0,1],[0,1],[0,1],[0,1]]]]]]]])
x = np.tile(A,reps=4)
print(x)

[[[[[[[[0 1 0 1 0 1 0 1]
       [0 1 0 1 0 1 0 1]
       [0 1 0 1 0 1 0 1]
       [0 1 0 1 0 1 0 1]
       [0 1 0 1 0 1 0 1]
       [0 1 0 1 0 1 0 1]
       [0 1 0 1 0 1 0 1]
       [0 1 0 1 0 1 0 1]]]]]]]]
