<a href="https://colab.research.google.com/github/wrixd/numpy_exercise/blob/main/22_Normalize_a_5x5_random_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import numpy as np

In [23]:
a = np.random.rand(5,5)

In [24]:
print(a)

[[0.67914701 0.22007293 0.41831774 0.7339277  0.10984624]
 [0.8116162  0.24208604 0.22205136 0.78271616 0.57370353]
 [0.62074681 0.64642937 0.69243334 0.22934186 0.65319219]
 [0.19460691 0.28474498 0.70516714 0.89625424 0.62790941]
 [0.94095312 0.87482933 0.01463558 0.04408162 0.16663285]]


In [25]:
min=np.min(a);max=np.max(a)

In [26]:
a=(a-min)/(max-min)

In [27]:
print(a)

[[0.71736894 0.22177854 0.43579241 0.77650707 0.10278403]
 [0.86037518 0.24554264 0.22391434 0.82917633 0.60353812]
 [0.65432338 0.68204882 0.73171211 0.23178475 0.68934958]
 [0.19428686 0.29159483 0.74545879 0.95174562 0.66205572]
 [1.         0.92861649 0.         0.03178828 0.16408765]]
