<a href="https://colab.research.google.com/github/wrixd/numpy_exercise/blob/main/24_Multiply_a_5x3_matrix_by_a_3x2_matrix_(real_matrix_product).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

In [8]:
a=np.random.rand(5,3);b=np.random.rand(3,2);print(a);print(b)

[[0.39939752 0.38741353 0.97273298]
 [0.71103411 0.61552016 0.31944069]
 [0.43991068 0.16738108 0.15642765]
 [0.27306342 0.34022515 0.46971826]
 [0.81180586 0.93127037 0.17399427]]
[[0.97993571 0.29198048]
 [0.9294327  0.69850705]
 [0.84035433 0.27232899]]


In [9]:
np.matmul(a,b)

array([[1.56889908, 0.65213076],
       [1.53729565, 0.72454621],
       [0.71810829, 0.28796198],
       [0.97853075, 0.44529675],
       [1.80728753, 0.93491407]])