<a href="https://colab.research.google.com/github/wrixd/numpy_exercise/blob/main/30_How_to_find_common_values_between_two_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np

In [10]:
a = np.random.randint(0,10,10)
print(a)
b = np.random.randint(0,10,10)
print(b)

[8 3 9 9 8 7 3 2 3 1]
[3 5 6 9 2 2 3 0 0 3]


In [11]:
print(np.intersect1d(a,b))

[2 3 9]
