<a href="https://colab.research.google.com/github/wrixd/numpy_exercise/blob/main/9_Create_a_3x3_matrix_with_values_ranging_from_0_to_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

In [6]:
a = np.random.randint(0,8,size=(3,3))
print(a)

[[5 3 1]
 [5 5 7]
 [6 3 0]]
